### ISSUE TITLE
Can't join the meeting in the mattermost Mobile app

### ISSUE THREAD

**Issue by wmysummer** [blindsidenetworks/mattermost-plugin-bigbluebutton#33] opened 2019-02-19 04:47 UTC
When creating bigbulebutton conference in mattermost，Mobile app could not join the meeting，No button to join the meeting is displayed。Display a string of characters，for example：#BigBuleButton #Off-Topic #ID1HNm6cw7FNLeAyTJeiee

**Comment by ffdixon** [comment] 2019-02-19 22:06
Can you post a screen shot.  We've not looked closely (yet!) into integrating with the Mattermost Mobile app.

**Comment by lsl061085** [comment] 2019-02-20 00:33
@ffdixon ![Image of mattermost](https://raw.githubusercontent.com/lsl061085/image/master/mattermost.png?token=AbnYmdFtkj7uGCNIdWqPzQzYqUBYYlAsks5cbJ9MwA%3D%3D)
  thanks！

**Comment by ffdixon** [comment] 2019-02-20 00:37
Hmm ... the image did not come through.  Can you cut-and-paste it into this issue.

**Comment by lsl061085** [comment] 2019-02-20 00:42
![mattermost](https://user-images.githubusercontent.com/28956825/53057667-4a4c8b00-34eb-11e9-9790-3b1bc514d876.png)
Sorry！

**Comment by jasonblais** [comment] 2019-02-25 19:38
Hey @lsl061085! Thanks for trying out the bigbluebutton plugin.

Currently there is limited support for plugins on mobile. Our team at Mattermost is planning to enhance the capabilities and achieve feature parity between desktop/browser and mobile in the coming months.

**Comment by sydneysider** [comment] 2019-03-03 08:10
Yea receiving same issue - would be awesome to get this on mobile. I know my company will expect this if/when we cut over to BBB.

Unfortunately this link: https://mattermost.com/blog/bigbluebutton-integration/

"Blindside Networks recommends using Firefox and Chrome for the best experience. For mobile users, the company recommends Android 6.0+ and iOS 11+."

Guessing this is in reference to your BBB app?

**Comment by ffdixon** [comment] 2019-03-03 13:17
We're actually getting close to a beta release for BigBlueButton 2.2, which will be a pure HTML5 client (no plugins, no app to install) that you can run on your mobile device.  If you have a Android 6.0+ and iOS 11+ phone/table, go to https://test.bigbluebutton.org/, give it a try, and let us know what you think.

**Comment by jsalatiel** [comment] 2019-05-30 05:03
@ffdixon, The html5 works just fine on mobile, but the problem mentioned in this **issue** is that if you create the bbb conference inside the mattermost desktop app, those using the mobile version will only see:
![image](https://user-images.githubusercontent.com/5522389/58609611-875cb200-827e-11e9-9439-d0308034e91a.png)
and thus wont be able to join, regardless  HTML5 client support.
The bbb plugin for mattermost could also output an url, so anyone using mobile version could click the link and join the conference. This would also fix #29 .

**Comment by jsalatiel** [comment] 2019-05-30 20:23
@ffdixon I just found out that i can actually "start" a conference from the mobile app by typing /bbb , i just can not join. So I think half of the problem is actually implemented, because no changes are needed in the mattermost android app itself. We only need that the mattermost plugin also output some url that we can click to be directed to the conference using chrome for example. My server already run bbb 2.2, so html 5 client is available.  Do you know if the URL would need to contain the secret for the bbb server ? If not,  would it be hard to add this url in the next version?

![image](https://user-images.githubusercontent.com/5522389/58661845-3ccf4a00-82ff-11e9-8e2e-e6cd7abbe254.png)

**Comment by ffdixon** [comment] 2019-05-30 22:34
Interesting!  Are you working with MatterMost on any current projects?  It should be possible to extend the MatterMost plugin to work with the android app, we would just need a bit of help on this one.

**Comment by jsalatiel** [comment] 2019-05-30 22:50
No, I am not a developer, I  am just a user of mattermost, bbb and mattermost-plugin-bigbluebutton.
Those tools are just great together, but I really miss the option to have a conference from my phone. I do not understand very well how this plugin works, but I supposed that '#ID1Ly4WTs..." that the plugin outputs on the android app is the ID of the conference it created on the server right? So, if instead outputting that, it outputs http://yourserver.com/bigbluebutton/api/join?meetingID=THATBIGNUMBER&checksum=CHECKSUMHERE, wouldn't work?
If it does, it would also kind of implement #29  and make easy to implement #40? ( Since now you know the server you have to connect to ), right ?

**Comment by iandriyanov** [comment] 2019-06-04 11:28
The same on mobile app (Mattermost server 5+, bbb 2.0, mattermost android app 1.19.0 build 193)

![123](https://user-images.githubusercontent.com/1125505/58875706-f0a45100-86d4-11e9-9430-c90a4ba56efc.jpg)

**Comment by jasonblais** [comment] 2019-06-04 11:55
Hey all! Currently there is limited support for plugins on mobile. Our team at Mattermost is planning to enhance the capabilities and achieve feature parity between desktop/browser and mobile in the coming months.

If anyone is interested and open to help extend support for plugins on mobile, come join us in the [public Mattermost Extensions channel](https://community.mattermost.com/core/channels/developer-toolkit)

**Comment by HarriLuxus** [comment] 2019-10-08 13:43
Has there been any developments on this?

**Comment by nicolailang** [comment] 2020-03-21 20:24
Still an issue - the problem is MM mobile app (I'm using iOS) does not show the "Join Meeting" button - as stated the mobile app is lagging behind. So for now the solution is to sign in to MM in a browser. :-(

**Comment by dfun90** [comment] 2020-04-22 13:58
We're also having this issue with the mobile client. The web/desktop app shows the "Join Meeting"-Button, on mobile there's only a hashtag with some Id.  

My idea for a workaround would be to have an optional config option that allows to specify that the BBB plugin posts an actual URL to the meeting besides the big blue shiny button. At least until Mattermost has proper integration for plugins inside the mobile client.  

I don't know about the specifics how the plugin ticks on the server side, but I can't imagine it would be too complex to add this feature. I will look into adding this in soon and/or report back/do a pull request!

**Comment by mkiszczyk** [comment] 2020-04-22 21:30
My workaround is to use a mattermost classic app. Its working there. Am using android 9.1. local mattermost server and bbb local server.

**Comment by rottaran** [comment] 2020-04-22 23:34
I was looking into it a few days ago. The plugin on server-side keeps an array of created bbb sessions without actually creating it on the bbb side. The mm client that clicks on the participate button triggers a small javascript, which generates a post request to the plugin's server side. The first client that reaches there triggers the actual creation of the bbb-session. I guess that the clients retrieve the bbb session URL and session token as answer and then open a new browser window to go there. The bbb link/token is unique to every participating client because it implements the access control / authentication.

In order to be usable as a normal participate link, the link would need to contain the post parameters in the URL as `?foo=bar...`. The plugin's server side can then answer with a redirect http status that points to the repective bbb session plus token. The mobile clients would open that participate link in a browser of their choice. Inside this browser, no mm authentication is present, hence they get redirected to the mm login-page first. Then, it depends on mm to redirect back correctly to the plugin's server URL after authentication. I had the feeling that this last step is broken in my deployment.

**Comment by javanaut-de** [comment] 2020-12-05 16:41
It seems that the classic app isn't working with the current version of the server (team edition) anymore. It is throwing an error message mentioning a possible SSL problem:

"Mattermost server unreachable, incompatible or SSL is not properly configured."

Can anyone confirm this or did my reverse proxy go nuts or something?

Greetings

**Comment by jasonblais** [comment] 2020-12-06 22:58
@javanaut-de Would this forum thread be helpful for your use case? (a similar error message was reported there) https://forum.mattermost.org/t/solved-android-app-connect-to-mattermost-team-link/1417/32

**Comment by split-brain-83** [comment] 2021-06-17 11:03
any chance to solve this issue? really appreciate any help on this.

**Comment by Joshndroid** [comment] 2021-06-17 11:22
> any chance to solve this issue? really appreciate any help on this.

This must just be dead... Seems to be the typical thing with some open source projects.. Just die as the issues pile up

**Comment by split-brain-83** [comment] 2021-06-17 12:17
> > any chance to solve this issue? really appreciate any help on this.
> 
> This must just be dead... Seems to be the typical thing with some open source projects.. Just die as the issues pile up

I can feel you. The root cause of this issue seems to be the plugins integration within the mobile app, which isn't finished yet. When this will get resolved, we can see the BBB meeting working.

**Comment by jdauphant** [comment] 2021-06-20 10:58
Maybe we can use the same API use by [Matterpoll](https://github.com/matterpoll/matterpoll) : 
![image](https://user-images.githubusercontent.com/1238254/122671457-efb0c000-d1c6-11eb-8fec-c5b8de61046a.png)

**Comment by harshilsharma63** [comment] 2021-06-21 03:37
Great idea @jdauphant . I'm exploring the possibility 👍

**Comment by harshilsharma63** [comment] 2021-06-27 11:17
A quick teaser of what's coming up-

https://user-images.githubusercontent.com/18575143/123542427-3eca9800-d767-11eb-8eb4-ef3eb1418b10.mp4

**Comment by jdauphant** [comment] 2021-06-28 07:28
nice ^^ :rocket:

**Comment by moschlar** [comment] 2021-07-20 19:18
Since this is now released as https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/releases/tag/v4.0.0 - this issue can be considered done, right?

**Comment by harshilsharma63** [comment] 2021-07-20 22:52
@moschlar yes absolutely 🎉

**Closed by harshilsharma63** 2021-07-20 22:52 UTC
Labels: help wanted

**Comment by ffdixon** [comment] 2021-07-21 00:59
Great work @harshilsharma63
