### ISSUE TITLE
Plugin Kills Mattermost "Plugin Marketplace" Page

### ISSUE THREAD

**Issue by frarude** [blindsidenetworks/mattermost-plugin-bigbluebutton#119] opened 2020-11-19 09:53 UTC
Mattermost latest version (5.30) after installing this plugin, the Plugin Marketplace stops to work. Only produces a blank page. 
No entries in the log file.
After removing the plugin the marketplace is working.

The Plugin itself seems to work.

**Comment by TI-Admin** [comment] 2020-11-20 16:06
I can confirm that the problem is also with Mattermost v5.29.
I didn't had this problem with Mattermost v5.28.

**Comment by TI-Admin** [comment] 2020-11-21 18:26
This is also reported and fixed for upcoming v2.2.0

[](https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/issues/116)

**Comment by harshilsharma63** [comment] 2020-11-26 05:06
@frarude Thanks for filing the bug. We'll get this resolved in the upcoming release.

**Closed** 2020-11-27 01:04 UTC
